FROM repos.peapod.com:5010/node:8.15.1-alpine as frontend

ENV FLAMESCOPE_VERSION v0.2.1
ENV FLAMESCOPE_REPO_URL https://github.com/martinwalsh/flamescope


WORKDIR /src
ADD . /src

RUN yarn install && \
      npm run webpack

FROM repos.peapod.com:5010/python:3.7.3-alpine3.9
COPY --from=frontend /src /src

RUN apk add --no-cache tini libmagic && \
      pip install -r /src/requirements.txt


WORKDIR /src
EXPOSE 5000/tcp

ENTRYPOINT ["/sbin/tini", "--"]
CMD ["/usr/local/bin/python", "run.py"]
